# NumPy Arrays: Creating Arrays

In [50]:
import numpy as np
import matplotlib.pylab as plt
from numpy import random

In [51]:
list_1 = [1, 2, 3, 4, 5]
np_arr_1 = np.array(list_1, dtype=np.int8)

np_arr_1

array([1, 2, 3, 4, 5], dtype=int8)

In [52]:
list_m_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np_arr_m_1 = np.array(list_m_1)

print("Multidimensional array data type:", np_arr_m_1.dtype)

np_arr_m_1

Multidimensional array data type: int64


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
# Return evenly spaced values within a given interval.
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [54]:
#Return evenly spaced numbers over a specified interval.
np.linspace(0, 5, 7)

array([0.        , 0.83333333, 1.66666667, 2.5       , 3.33333333,
       4.16666667, 5.        ])

In [55]:
np.zeros(4)

array([0., 0., 0., 0.])

In [56]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [70]:
# np.random.randint?
np.random.randint(10, 50, size=(2,3))

array([[21, 24, 30],
       [43, 46, 13]])