# Creating Arrays

In [3]:
import numpy as np
import matplotlib.pylab as plt
from numpy import random

In [5]:
list_1 = [1, 2, 3, 4, 5]
np_arr_1 = np.array(list_1, dtype=np.int8)

np_arr_1

array([1, 2, 3, 4, 5], dtype=int8)

In [7]:
list_m_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np_arr_m_1 = np.array(list_m_1)

print("Multidimensional array data type:", np_arr_m_1.dtype)

np_arr_m_1

Multidimensional array data type: int64


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# Return evenly spaced values within a given interval.
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [12]:
# Return evenly spaced numbers over a specified interval.
np.linspace(0, 5, 7)

array([0.        , 0.83333333, 1.66666667, 2.5       , 3.33333333,
       4.16666667, 5.        ])

In [14]:
np.zeros(4)

array([0., 0., 0., 0.])

In [16]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
# np.random.randint?
np.random.randint(10, 50, size=(2,3))

array([[36, 41, 48],
       [47, 13, 37]])

# Slicing & Indexes

In [34]:
np_arr_1

array([1, 2, 3, 4, 5], dtype=int8)

In [44]:
np_arr_m_1

array([[42, 10,  3],
       [24, 10,  6],
       [ 7, 10,  9]])

In [21]:
np_arr_m_1[1, 2]

6

In [23]:
np_arr_m_1.item(1, 2)

6

In [25]:
np_arr_m_1.shape

(3, 3)

In [27]:
np_arr_m_1[0, 0] = 42
np_arr_m_1.itemset((1, 0), 24)

In [30]:
np.take(np_arr_m_1, [2, 5, 8])

array([3, 6, 9])

In [35]:
np.put(np_arr_m_1, [1, 4, 7], [10, 10, 10])

In [37]:
np_arr_1[:5:2]

array([1, 3, 5], dtype=int8)

In [41]:
# Get third element from each row of a multidimensional array
np_arr_m_1[:,2]

array([3, 6, 9])

In [46]:
# Flip multidimensional array
np_arr_m_1[::-1]

array([[ 7, 10,  9],
       [24, 10,  6],
       [42, 10,  3]])

In [54]:
# Get even values from multidimensional array
np_arr_m_1[np_arr_m_1 % 2 == 0]

array([42, 10, 24, 10,  6, 10])

In [52]:
# Get values from multidimensional array that are greater than 5 and lees than 9
np_arr_m_1[(np_arr_m_1 > 5) & (np_arr_m_1 < 9)]

array([6, 7])

In [53]:
# Get unique values from multidimensional array
np.unique(np_arr_m_1)

array([ 3,  6,  7,  9, 10, 24, 42])