# Creating Arrays

In [1]:
import numpy as np
import matplotlib.pylab as plt
from numpy import random

In [2]:
list_1 = [1, 2, 3, 4, 5]
np_arr_1 = np.array(list_1, dtype=np.int8)

np_arr_1

array([1, 2, 3, 4, 5], dtype=int8)

In [3]:
list_m_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np_arr_m_1 = np.array(list_m_1)

print("Multidimensional array data type:", np_arr_m_1.dtype)

np_arr_m_1

Multidimensional array data type: int64


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# Return evenly spaced values within a given interval.
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [5]:
# Return evenly spaced numbers over a specified interval.
np.linspace(0, 5, 7)

array([0.        , 0.83333333, 1.66666667, 2.5       , 3.33333333,
       4.16666667, 5.        ])

In [6]:
np.zeros(4)

array([0., 0., 0., 0.])

In [7]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
# np.random.randint?
np.random.randint(10, 50, size=(2,3))

array([[29, 30, 42],
       [16, 35, 20]])

# Slicing & Indexes

In [9]:
np_arr_1

array([1, 2, 3, 4, 5], dtype=int8)

In [10]:
np_arr_m_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# Retrieve element at pos 1,2 using array indices
np_arr_m_1[1, 2]

6

In [12]:
# Retrieve element at pos 1,2 using tuple as element location
np_arr_m_1.item(1, 2)

6

In [13]:
# Get tuple of array one dimensions
np_arr_m_1.shape

(3, 3)

In [14]:
# Set element value at pos 0,0 = 42 using array indices
np_arr_m_1[0, 0] = 42
# Set element value at pos 1,0 = 24 using tuple as element location
np_arr_m_1.itemset((1, 0), 24)

In [15]:
# Take elements from an array using indices of the values to extract (2,5,8).
np.take(np_arr_m_1, [2, 5, 8])

array([3, 6, 9])

In [16]:
# Replace specified elements of an array with given values using target indices and values to place in a at target indices (1,4,7) => (10,10,10).
np.put(np_arr_m_1, [1, 4, 7], [10, 10, 10])

In [17]:
# Slice one-dimensional array from the start until 5th element with step 2
np_arr_1[:5:2]

array([1, 3, 5], dtype=int8)

In [18]:
# Get third element from each row of a multidimensional array
np_arr_m_1[:,2]

array([3, 6, 9])

In [19]:
# Flip multidimensional array
np_arr_m_1[::-1]

array([[ 7, 10,  9],
       [24, 10,  6],
       [42, 10,  3]])

In [20]:
# Get even values from multidimensional array
np_arr_m_1[np_arr_m_1 % 2 == 0]

array([42, 10, 24, 10,  6, 10])

In [21]:
# Get values from multidimensional array that are greater than 5 and lees than 9
np_arr_m_1[(np_arr_m_1 > 5) & (np_arr_m_1 < 9)]

array([6, 7])

In [22]:
# Get unique values from multidimensional array
np.unique(np_arr_m_1)

array([ 3,  6,  7,  9, 10, 24, 42])

# Reshaping Arrays

In [23]:
np_arr_m_1

array([[42, 10,  3],
       [24, 10,  6],
       [ 7, 10,  9]])

In [24]:
# Reshape array into nine items single axis array
np_arr_m_1.reshape((1, 9))

array([[42, 10,  3, 24, 10,  6,  7, 10,  9]])

In [25]:
# Resize to (2, 5)
np.resize(np_arr_m_1, (2, 5))

array([[42, 10,  3, 24, 10],
       [ 6,  7, 10,  9, 42]])

In [26]:
# Transpose Array
np_arr_m_1.transpose()

array([[42, 24,  7],
       [10, 10, 10],
       [ 3,  6,  9]])

In [27]:
# Swap axes 0 and 1
np_arr_m_1.swapaxes(0, 1)

array([[42, 24,  7],
       [10, 10, 10],
       [ 3,  6,  9]])

In [28]:
# Flatten array in row order
np_arr_m_1.flatten()

array([42, 10,  3, 24, 10,  6,  7, 10,  9])

In [29]:
# Flatten array in column order
np_arr_m_1.flatten('F')

array([42, 24,  7, 10, 10, 10,  3,  6,  9])

# Stacking & Splitting

In [30]:
# Create square matrix of size 2 filled with random integes with maximum value of 10
ss_arr_1 = np.random.randint(10, size=(2, 2))
print("ss_arr_1\n", ss_arr_1)

# Same operation for further calculations
ss_arr_2 = np.random.randint(10, size=(2, 2))
print("ss_arr_2\n", ss_arr_2)

ss_arr_1
 [[5 0]
 [1 8]]
ss_arr_2
 [[9 4]
 [4 8]]


In [31]:
# Vertically stack array one on top of array two
np.vstack((ss_arr_1, ss_arr_2))

array([[5, 0],
       [1, 8],
       [9, 4],
       [4, 8]])

In [32]:
# Horisontally stack array one on with array two
np.hstack((ss_arr_1, ss_arr_2))

array([[5, 0, 9, 4],
       [1, 8, 4, 8]])

In [33]:
# Stack 1-D arrays as columns into a 2-D array.
np.column_stack((np.array((1, 2, 3)), np.array((4, 5, 6))))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [34]:
# Stack array one and two in sequence vertically (row wise).
np.row_stack((ss_arr_1, ss_arr_2))

array([[5, 0],
       [1, 8],
       [9, 4],
       [4, 8]])

In [36]:
# Delete second row of array one and two
ss_arr_3 = np.delete(ss_arr_1, 1, 0)
print("ss_arr_3\n", ss_arr_3)

ss_arr_4 = np.delete(ss_arr_2, 1, 0)
print("ss_arr_4\n", ss_arr_4)

ss_arr_3
 [[5 0]]
ss_arr_4
 [[9 4]]


In [41]:
ss_arr_5 = np.random.randint(10, size=(2, 10))
print("ss_arr_5\n", ss_arr_5)

# Split an array into five sub-arrays horizontally (column-wise).
np.hsplit(ss_arr_5, 5)

ss_arr_5
 [[2 3 8 7 3 1 3 3 9 5]
 [1 2 2 5 1 1 7 5 3 9]]


[array([[2, 3],
        [1, 2]]),
 array([[8, 7],
        [2, 5]]),
 array([[3, 1],
        [1, 1]]),
 array([[3, 3],
        [7, 5]]),
 array([[9, 5],
        [3, 9]])]

In [43]:
# Split an array horizontally into section sub-arrays of size 2, 3 and a "remainder" section subarray.
np.hsplit(ss_arr_5, (2, 5))

[array([[2, 3],
        [1, 2]]),
 array([[8, 7, 3],
        [2, 5, 1]]),
 array([[1, 3, 3, 9, 5],
        [1, 7, 5, 3, 9]])]